name: Package-Deploy

on:
  workflow_dispatch:
  
jobs:  
  depoy-packages:
    runs-on: windows-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Pack
      run: dotnet pack .\NetMsixUpdaterFormsComponent\ -o out
      
    - name: Push to GH Pakcages
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.GH_PACKAGE_PAT }} --source "https://nuget.pkg.github.com/LuanRoger/index.json" --skip-duplicate
        
  deploy-nuget:
    runs-on: windows-latest
    environment: production
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Pack
      run: dotnet pack .\NetMsixUpdaterFormsComponent\ -o out
      
    - name: Push to Nuget
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NMUFC_NUGET_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
